version: "3.9"

services:
  tools_redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - ${PUBLIC_RI_PORT}:5540
    volumes:
      - ${LOCAL_RI_PATH}:/db
    networks:
      - internal_app_communication


networks:
  internal_app_communication:
    external: true
