version: '3.4'

services:

  mysql_db:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${LOCAL_PATH}:/var/lib/mysql
    ports:
      - 3306:3306

    command: --default-authentication-plugin=mysql_native_password
    networks:
      - internal_app_communication  

networks:
  internal_app_communication:
    external: true
