version: '3.4'

services:

  damp_mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ${LOCAL_DB_PATH}:/var/lib/mysql
    ports:
      - ${LOCAL_DB_PORT}:3306

  damp_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    ports:
      - ${PUBLIC_PMA_PORT}:80

  damp_php:
    image: tanmaysarkar/damp_php:${DAMP_PHP_VERSION}
    volumes:
        - ${LOCAL_WWW_PATH}:/var/www/html/
        - ${LOCAL_PHP_LOG_PATH}:/var/www/html/logs
    ports:
        - ${APP_PORT}:80
               