version: '3.4'

services:

  mongo_db:
    image: mongo:8.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=product
    volumes:
      - ${LOCAL_PATH}:/data/db
    networks:
      - ${DOCKER_NETWORK_NAME}  
  mongo-express:
    image: mongo-express
    ports:
      - ${PUBLIC_ME_PORT}:8081
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - ${DOCKER_NETWORK_NAME}
    depends_on:
      - mongo_db

networks:
  docker_network:
    name: ${DOCKER_NETWORK_NAME}
    external: true