version: "3"

services:
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/${PG_DATABASE}
      SONAR_JDBC_USERNAME: ${PG_USER}
      SONAR_JDBC_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PUBLIC_SQ_PORT}:9000
    volumes:
      - "X:/doc_vol/sonar/conf:/opt/sonarqube/conf"
      - "X:/doc_vol/sonar/data:/opt/sonarqube/data"
      - "X:/doc_vol/sonar/extensions:/opt/sonarqube/extensions"
      - "X:/doc_vol/sonar/logs:/opt/sonarqube/logs"
      - "X:/doc_vol/sonar/temp:/opt/sonarqube/temp"

  sonar_db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - "X:/doc_vol/sonar/db:/var/lib/postgresql"
      - "X:/doc_vol/sonar/dbdata:/var/lib/postgresql/data"

