version: '3.4'

services:
  tools_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    ports:
      - ${PUBLIC_PMA_PORT}:80
    networks:
      - internal_app_communication

networks:
  internal_app_communication: