version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - ${PUBLIC_JK_PORT}:8080
     - ${PUBLIC_JK_MS_PORT}:50000
    volumes:
     - "X:/doc_vol/jenkins/conf:/var/jenkins_home"
     - "X:/doc_vol/jenkins/dock:/var/run/docker.sock"

