version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - ${PUBLIC_JK_PORT}:8080
     - ${PUBLIC_JK_MS_PORT}:50000
    volumes:
     - jenkins_config:/var/jenkins_home
     - jenkins_dock:/var/run/docker.sock

volumes:
  jenkins_config:
  jenkins_dock: