version: "3.9"

services:
  redis:
    image: redis:7.4
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ${LOCAL_REDIS_PATH}:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - internal_app_communication

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - ${PUBLIC_RI_PORT}:8001
    depends_on:
      - redis
    volumes:
      - ${LOCAL_RI_PATH}:/db
    networks:
      - internal_app_communication


networks:
  internal_app_communication:
    external: true
