version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RBMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RBMQ_PASSWORD}
    ports:
      - 5672:5672
      - 9952:15672
    volumes:
      - ${Local_RBMQ_Data}:/var/lib/rabbitmq/
      - ${Local_RBMQ_LOG}:/var/log/rabbitmq
    networks:
      - internal_app_communication


networks:
  internal_app_communication:
    external: true   