version: "3"

services:
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/${PG_DATABASE}
      SONAR_JDBC_USERNAME: ${PG_USER}
      SONAR_JDBC_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PUBLIC_SQ_PORT}:9000
    volumes:
      - ${SONAR_PATH}/conf:/opt/sonarqube/conf
      - ${SONAR_PATH}/data:/opt/sonarqube/data
      - ${SONAR_PATH}/extensions:/opt/sonarqube/extensions
      - ${SONAR_PATH}/logs:/opt/sonarqube/logs
      - ${SONAR_PATH}/temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ${SONAR_PATH}/postgresql:/var/lib/postgresql
      - ${SONAR_PATH}/postgresql_dbdata:/var/lib/postgresql/data

