version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # Disable security for local/dev
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${LOCAL_PATH}:/usr/share/elasticsearch/data
    ports:
      - ${PUBLIC_ELASTICSEARCH_PORT}:9200
    networks:
      - internal_app_communication  

networks:
  internal_app_communication:
    external: true      